// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProj.Server;

namespace MyProj.Server.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("MyProj.Shared.Data.Booklet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lesson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Professor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Booklets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "گسسته",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "وصال حکمی"
                        },
                        new
                        {
                            Id = 2L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "گسسته",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "رضا انتظاری ملکی"
                        },
                        new
                        {
                            Id = 3L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "مبانی کامپیوتر",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "صالح اعتمادی"
                        },
                        new
                        {
                            Id = 4L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "مبانی کامپیوتر",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "مرضیه ملکی مجد"
                        },
                        new
                        {
                            Id = 5L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "طراحی بازیهای کامپیوتری",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "زینب موحدی"
                        },
                        new
                        {
                            Id = 6L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "برنامه نویسی پیشرفته",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "صالح اعتمادی"
                        },
                        new
                        {
                            Id = 7L,
                            College = "مهندسی کامپیوتر",
                            Lesson = "برنامه نویسی پیشرفته",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "مرضیه ملکی مجد"
                        },
                        new
                        {
                            Id = 8L,
                            College = "ریاضی",
                            Lesson = "ریاضی2",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "سمانه مشهدی"
                        },
                        new
                        {
                            Id = 9L,
                            College = "ریاضی",
                            Lesson = "ریاضی2",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "مهدی نجفی خواه"
                        },
                        new
                        {
                            Id = 10L,
                            College = "ریاضی",
                            Lesson = "ریاضی2",
                            Link = "Nadjafikhah - Calculus II - Persian.pdf",
                            Professor = "محمد یعقوبی فر"
                        });
                });

            modelBuilder.Entity("MyProj.Shared.Data.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MyProj.Shared.Data.Professor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendanceRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BehaviorRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingRate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VoteNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی کامپیوتر",
                            ExamRate = 0,
                            Name = "مهرداد آشتیانی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 2L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی کامپیوتر",
                            ExamRate = 0,
                            Name = "رضا انتظاری",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 3L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی کامپیوتر",
                            ExamRate = 0,
                            Name = "سعید پارسا",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 4L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی کامپیوتر",
                            ExamRate = 0,
                            Name = "مرضیه ملکی مجد",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 5L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی کامپیوتر",
                            ExamRate = 0,
                            Name = "صالح اعتمادی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 6L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی صنایع",
                            ExamRate = 0,
                            Name = "فرناز برزین پور",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 7L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی صنایع",
                            ExamRate = 0,
                            Name = "رسول نورالنساء",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 8L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی صنایع",
                            ExamRate = 0,
                            Name = "محمد سعیدی مهرآباد",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 9L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی صنایع",
                            ExamRate = 0,
                            Name = "مهدی حیدری",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 10L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی برق",
                            ExamRate = 0,
                            Name = "کریم محمدی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 11L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی برق",
                            ExamRate = 0,
                            Name = "محمدنژاد",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 12L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی برق",
                            ExamRate = 0,
                            Name = "موسوی میرکلایی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 13L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی برق",
                            ExamRate = 0,
                            Name = "یاوند حسنی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 14L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "معماری و شهرسازی",
                            ExamRate = 0,
                            Name = "مصطفی بهزادفر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 15L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "معماری و شهرسازی",
                            ExamRate = 0,
                            Name = "محسن فیضی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 16L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "معماری و شهرسازی",
                            ExamRate = 0,
                            Name = "اصغر محمدمرادی",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 17L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "معماری و شهرسازی",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 18L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی پیشرفت",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 19L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی خودرو",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 20L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی راه آهن",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 21L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی شیمی",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 22L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی عمران",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 23L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی مکانیک",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 24L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "مهندسی مواد و متالوژی",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 25L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "ریاضی",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 26L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "فیزیک",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 27L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "زبان",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 28L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "تربیت بدنی",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        },
                        new
                        {
                            Id = 29L,
                            AttendanceRate = 0,
                            BehaviorRate = 0,
                            College = "معارف",
                            ExamRate = 0,
                            Name = "محسن وفامهر",
                            ScoreRate = 0,
                            TeachingRate = 0,
                            VoteNum = 0L
                        });
                });

            modelBuilder.Entity("MyProj.Shared.Data.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
